### PR TITLE
Log each arbitrage to a csv file

### PR DESCRIPTION
**Pull request by dazito**

### CODE REVIEW

**Comment by dazito** [comment]
I avoided using a CSV library because all I know of would use in some way reflection and I want to avoid it so that the app is as fast as possible. 

Speed is rather important factor when trading online. Let me know what you think.

PS; Can you tell me why the build failed?

**Comment by scionaltera** [comment]
> PS; Can you tell me why the build failed?

```
java.lang.AssertionError: Number of elements (columns) per line does not match the number of columns expected:<14> but was:<12>
142 | at org.junit.Assert.fail(Assert.java:89)
143 | at org.junit.Assert.failNotEquals(Assert.java:835)
144 | at org.junit.Assert.assertEquals(Assert.java:647)
145 | at com.r307.arbitrader.service.TradingServiceTest.testLogArbitrageToCsv(TradingServiceTest.java:428)
```

This happened during pitest and not during the regular JUnit run, which is a little strange. Let's start by merging `master` back into your branch and see if it still happens. If it does I'm sure I can help get it straightened out.

**Comment by dazito** [comment]
Yeah it also failed here (on `gradle clean build`) with the same message. It's weird where this extra field comes from, the class only has 13 fields... unless for some reason outside my knowledge, the `class ArbitrageLogBuilder` counts has an extra field during gradle build time :confused:

**Comment by scionaltera** [comment]
I had some time to look at the branch to see why it fails in pitest and I think this is what is problematic:

```
final int numberOfFields = ArbitrageLog.class.getDeclaredFields().length - 1;
```

When it runs outside of pitest it seems to get the expected value of 12, but inside pitest it returns 14. I was able to get it to print out the names of the extra fields: `$pitCoverageProbes, $$pitCoverageProbeSize`.

I think the easiest fix here would be to just use a constant value instead of reflection for the expected number of fields, and to use the fields explicitly in `ArbitrageLog.java` instead of `getDeclaredFields()`. That way to add more fields you'd have to do it manually and update the test. A little less convenient but a lot more predictable behavior. I don't expect the field list here to be changing all that often.

**Comment by dazito** [comment]
Thanks for finding out the root cause. Just pushed the fix, all green now :heavy_check_mark:

**Pull request merged**
